version: '3.9'

networks:
  demo-net:
    driver: bridge
    name: demo
volumes:
  demo_mssql:

services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest.
    container_name: c-mssql
    ports:
      - "1433:1433"
    volumes:
      - demo_mssql:/var/opt/mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Admin1234
    networks:
      - demo-net
  service-demo:
    depends_on:
      - db
    build:
      context: .
    container_name: demo-java
    ports:
      - "8080:8080"
    networks:
      - demo-net

