version: '3.9'

networks:
  demo-net:
    driver: bridge
    name: demo

services:
  db_mysql:
    image: mysql:8.4.3
    container_name: c-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - demo-net
  service:
    depends_on:
      - db_mysql
    environment:
      SPRING_CONFIG_LOCATION: /project/config/application.properties
    build:
      context: .
    container_name: c-java
    ports:
      - "8080:8080"
    volumes:
      - ./config:/project/config
    networks:
      - demo-net

